### ISSUE TITLE
Custom Helpers Guide - load_paths order issue

### ISSUE THREAD

**Issue by fgi** [lotus/lotus.github.io#112]
Following the example in Custom Helpers Guide (http://lotusrb.org/guides/helpers/custom-helpers/), I had an application loading error: 
`uninitialized constant Web::Helpers (NameError)`
with Lotus v0.5.0 and Ruby 2.2.3.

It seems to be related to the loading order defined in application.rb file: 
```
# apps/web/application.rb
      # ...

      load_paths << [
        'controllers',
        'views',
        'helpers'
      ]
# ...

      view.prepare do
        include Lotus::Helpers
        include Web::Helpers::Shuffler
      end
```
I guess helpers must be loaded before views before being included into them.
Inserting `'helpers'` on top of `load_paths` fixed the issue:
```
# apps/web/application.rb
      # ...

      load_paths << [
        'helpers',
        'controllers',
        'views'
      ]
# ...
```
I this is right, could you fix the guide?
Thanks.

**Comment by jodosha** [comment]
@fgi Hello! Thanks for this good catch. That is the reason why the load order is explicit: to guarantee flexibility. Fixed :+1:
